services:
  - type: web
    name: bank-account-management-system
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
